name: Patrolling My Contribution
on: workflow_dispatch

jobs:
  patrolling:
    runs-on: ubuntu-latest
    steps:
      - name: Set datetime range
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "RANGE_START=$(date --utc --iso-8601='seconds' -d 'today 00:00:00')" >> $GITHUB_ENV
          echo "RANGE_END=$(date --utc --iso-8601='seconds')" >> $GITHUB_ENV

      - name: Get contribution
        uses: octokit/graphql-action@v2.x
        id: get_my_contribution
        with:
          # https://docs.github.com/ja/graphql/reference/queries#user
          query: |
            query contributions(
              $user: String! 
              $from: DateTime!
              $to: DateTime!
            ) {
              user(login: $user) {
                contributionsCollection(to:$to, from:$from) {
                  contributionCalendar {
                    weeks {
                      contributionDays {
                        date
                        contributionCount
                      }
                    }
                  }
                }
              }
            }
          variables: |
            user: ${{ github.actor }}
            from: ${{ env.RANGE_END }}
            to: ${{ env.RANGE_START }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'data: ${{ steps.get_my_contribution.outputs.data }}'"