name: Patrolling My Contribution
on:
  workflow_dispatch:
  schedule:
    - cron: '30 13 * * *'

jobs:
  patrolling:
    runs-on: ubuntu-latest
    steps:
      - name: Set datetime range
        id: set_datetime_range
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "RANGE_START=$(date --utc --iso-8601='seconds' -d 'today 00:00:00')" >> "${GITHUB_OUTPUT}"
          echo "RANGE_END=$(date --utc --iso-8601='seconds')" >> "${GITHUB_OUTPUT}"

      - name: Get contribution
        uses: octokit/graphql-action@v2.x
        id: get_my_contribution
        with:
          # https://docs.github.com/ja/graphql/reference/queries#user
          query: |
            query contributions(
              $user: String! 
              $from: DateTime!
              $to: DateTime!
            ) {
              user(login: $user) {
                contributionsCollection(to:$to, from:$from) {
                  contributionCalendar {
                    weeks {
                      contributionDays {
                        date
                        contributionCount
                      }
                    }
                  }
                }
              }
            }
          variables: |
            user: ${{ github.actor }}
            from: ${{ steps.set_datetime_range.outputs.RANGE_END }}
            to: ${{ steps.set_datetime_range.outputs.RANGE_START }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse and get contributions count
        id: parse_contributions_count
        run: |
          CONTRIBUTIONS_COUNT=$(echo '${{ steps.get_my_contribution.outputs.data }}' | jq '.user.contributionsCollection.contributionCalendar.weeks[].contributionDays[].contributionCount')
          echo "Today's contributions count: $CONTRIBUTIONS_COUNT"
          echo "TODAY_CONTRIBUTIONS_COUNT=$CONTRIBUTIONS_COUNT" >> "${GITHUB_OUTPUT}"

      - name: Post contributions count to slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Today's contributions count
          SLACK_COLOR: good
          SLACK_MESSAGE: Today's contributions count is 【 ${{ steps.parse_contributions_count.outputs.TODAY_CONTRIBUTIONS_COUNT }} 】.